id: node.field_locations
uuid: fd3e52dd-0976-44f4-ad00-cf98f9c20784
status: true
langcode: en
name: field_locations
entity_type: node
type: bethel_location
settings: {  }
module: bethel_location
active: true
locked: false
cardinality: '-1'
translatable: false
indexes: {  }
