id: node.podcast.default
uuid: adb76b41-6490-40f1-b441-6542e3b7d1a2
targetEntityType: node
bundle: podcast
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: '4'
    settings:
      rows: '9'
      summary_rows: '3'
      placeholder: ''
  field_copyright:
    type: text_textfield
    weight: '6'
    settings:
      size: '60'
      placeholder: ''
  field_image:
    type: image_image
    weight: '3'
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
  field_tags:
    type: taxonomy_autocomplete
    weight: '5'
    settings:
      size: '60'
      autocomplete_route_name: taxonomy.autocomplete
      placeholder: ''
  field_vimeo:
    type: text_textfield
    weight: '2'
    settings:
      size: '60'
      placeholder: ''
  title:
    weight: '0'
    visible: true
  field_type:
    type: options_select
    weight: '1'
    settings: {  }
status: true
