id: node.field_copyright
uuid: be5c490e-155a-4a54-9100-bc0f1e70a9aa
status: '1'
langcode: en
name: field_copyright
entity_type: node
type: text
settings:
  max_length: '255'
module: text
active: '1'
locked: '0'
cardinality: '1'
translatable: '0'
indexes: {  }
