id: user.user.user_picture
uuid: 90bbb3c7-8d53-4b2b-9300-d3ac8c293fe5
status: '1'
langcode: en
field_uuid: 05bdc132-374b-4b15-9e2a-42cdf97ae24a
entity_type: user
bundle: user
label: Picture
description: 'Your virtual face or picture.'
required: '0'
default_value: {  }
default_value_function: ''
settings:
  file_directory: pictures
  file_extensions: 'png gif jpg jpeg'
  max_filesize: ''
  max_resolution: ''
  min_resolution: ''
  alt_field: '0'
  alt_field_required: '0'
  title_field: '0'
  title_field_required: '0'
  default_image: '1'
field_type: image
