id: node.field_vimeo
uuid: 104a62c9-ac61-49f6-bb21-33e489f0a55b
status: '1'
langcode: en
name: field_vimeo
entity_type: node
type: text
settings:
  max_length: '255'
module: text
active: '1'
locked: '0'
cardinality: '1'
translatable: '0'
indexes: {  }
