id: node.podcast.field_image
uuid: cbe8a1d6-0816-4df5-b401-1e8e8e9724a3
status: true
langcode: en
field_uuid: 100dbe77-602c-4995-8837-55d124781182
entity_type: node
bundle: podcast
label: 'Cover Art'
description: 'Square cover image for iTunes.  Any image uploaded will be automatically resized to 1400x1400 pixels.'
required: 0
default_value: {  }
default_value_function: ''
settings:
  file_directory: podcast
  file_extensions: 'png gif jpg jpeg'
  max_filesize: ''
  max_resolution: ''
  min_resolution: ''
  alt_field: 0
  alt_field_required: 0
  title_field: 0
  title_field_required: 0
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
field_type: image
