id: node.podcast.teaser
uuid: 7c214194-512c-413b-8800-d6e4ff78707b
targetEntityType: node
bundle: podcast
mode: teaser
content:
  field_image:
    type: image
    weight: '0'
    settings:
      image_style: thumbnail
      image_link: content
    label: hidden
  language:
    visible: false
  body:
    type: text_default
    weight: '1'
    settings: {  }
    label: hidden
hidden:
  field_tags: true
  field_type: true
  field_vimeo: true
  field_copyright: true
  langcode: true
status: true
