id: node.podcast.default
uuid: 57faf9ac-ebd8-455e-8a00-a01fbd2bc5e0
targetEntityType: node
bundle: podcast
mode: default
content:
  language:
    visible: false
  field_image:
    type: image
    weight: '0'
    settings:
      image_style: coverart_thumb
      image_link: ''
    label: hidden
  body:
    type: text_default
    weight: '1'
    settings: {  }
    label: hidden
  field_copyright:
    type: text_default
    weight: '2'
    settings: {  }
    label: hidden
hidden:
  field_tags: true
  field_type: true
  field_vimeo: true
  langcode: true
status: true
