id: node.field_image
uuid: 100dbe77-602c-4995-8837-55d124781182
status: true
langcode: en
name: field_image
entity_type: node
type: image
settings:
  uri_scheme: public
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
  column_groups:
    file:
      label: File
      columns:
        - target_id
        - width
        - height
    alt:
      label: Alt
      translatable: true
    title:
      label: Title
      translatable: true
module: image
active: true
locked: false
cardinality: '1'
translatable: false
indexes: {  }
