type: podcast
uuid: 38fcdfbf-92a0-43d3-af30-8395cba668d4
name: Podcast
description: 'Content type for Podcaster structure.'
help: ''
has_title: true
title_label: Title
settings:
  node:
    preview: '1'
    options:
      status: status
      promote: promote
      sticky: '0'
      revision: '0'
    submitted: true
status: true
langcode: en
